# -*- coding: utf-8 -*-
"""Lambda.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CMnJnkP-DPrXdiHPkAySmQB73MkZMvRe
"""

#python train.py --dataset [path] --size 32*32 --model_path [path]
x = lambda a : a + 10
print(x(5))

x = lambda a, b, c: a *b*c
print(x(5,6,9))

def myfunc(n):
  return lambda a :a*n # lambda spk func
mydouble = myfunc(2) #n=2 #variable = func(n)
mytriple = myfunc(3) #n=3
print(mydouble(11))
print(mytriple(11))

# API with multiple end points
# dealing development of softwares and logics